name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch: ~

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby-version: ['3.1', '3.2', '3.3']

    runs-on: ${{ matrix.os }}
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v4

    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby-version }}
        bundler-cache: true

    - uses: actions/setup-node@v3

    - uses: browser-actions/setup-chrome@latest
    - uses: nanasess/setup-chromedriver@master

    - name: Run tests
      run: bundle exec rake test
      timeout-minutes: 5

    - name: Upload test artifacts
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: test-artifacts
        path: tmp
